name: schedule 서버의 CI/CD 설정

on:
  push:
    branches: [ "schedule" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: test with Gradle Wrapper
        run: ./gradlew :schedule:presentation:test

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew :schedule:presentation:build

      - name: Scp jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SSH_schedule}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: |
            schedule/presentation/build/libs/${{secrets.SCHEDULE_JAR}}.jar
          target: schedule/
          strip_components: 4

      - name: Scp Dockerfile to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: |
            schedule/Dockerfile
          target: schedule/
          strip_components: 1

      - name: Scp docker-compose.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: |
            schedule/docker-compose.yml
          target: schedule/
          strip_components: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Deploy Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SERVER_IP}} << 'EOF'
          cd schedule
          docker stop schedule || true && docker rm schedule || true && docker rmi schedule:1.0.0 || true
          docker build -t schedule:1.0.0 .
          docker-compose up -d
          EOF
